name: Build AWS Sec Quiz

on:
  workflow_dispatch:            # run manually
  push:
    paths:
      - 'aws-quiz-src/**'       # auto-run when any source file changes

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # allow the Action to push build output

    defaults:
      run:
        working-directory: aws-quiz-src

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Build with Vite
        run: npm run build

      - name: Commit build
        run: |
          # Configure Git for the Action
          git config --global user.email "action@github.com"
          git config --global user.name  "GitHub Action"

          # Add the freshly built AWS quiz folder
          git add -f "../docs/aws-quiz"

          # Commit only if there are changes staged
          git diff --quiet --cached || git commit -m "Build aws-quiz"

          # Push back to main
          git push
