name: Build SysOps Quiz

on:
  workflow_dispatch:
  push:
    paths:
      - 'aws-sysops-quiz-src/**'

jobs:
  build-sysops-quiz:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: aws-sysops-quiz-src

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Build with Vite
        run: npm run build

      - name: Commit build
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name  "GitHub Action"

          # Output folder name = “aws-sysops-quiz”
          git add -f "../docs/aws-sysops-quiz"
          git diff --quiet --cached || git commit -m "Build aws-sysops-quiz"
          git push
